### PR TITLE
[#3417] Remove doc of outdated versions

### PR DESCRIPTION
**Pull request by avgustinmm**
Removed versions from 1.0 to 1.11 from documentation.

Signed-off-by: Marinov Avgustin <Avgustin.Marinov@bosch.io

### CODE REVIEW

**Review by sophokles73 — APPROVED** [review]
LGTM

**Comment by sophokles73** [comment]
@avgustinmm Can you please add a corresponding entry to the release notes?

**Comment by avgustinmm** [comment]
Added entry in release notes for 2.2.0

**Comment by sophokles73** [comment]
@avgustinmm is there a particular reason why you use different mail addresses for author vs signed-off-by?

**Comment by avgustinmm** [comment]
I used different addresses by mistake. I fixed address.

**Pull request merged**
