### PR TITLE
Fix broken links on website

### PR DESCRIPTION
**Pull request by sophokles73**
This should fix most (if not all) broken links as reported in #3413

### CODE REVIEW

**Comment by calohmn** [comment]
To be fixed "Getting started" links still in 
site/documentation/content/dev-guide/custom_http_adapter.md
site/documentation/content/_index.md

These also occur in the older version branches. Maybe we could just do a search & replace of "https://www.eclipse.org/hono/getting-started/" after generating website files in the website deployment pipeline.

**Comment by sophokles73** [comment]
> site/documentation/content/dev-guide/custom_http_adapter.md

Can you provide a line number? I do not see any broken links anymore ...

**Comment by calohmn** [comment]
> reducing the cherry-picking effort on the older branches

I would suggest cherry-picking only from version 1.12 onwards, the `Getting started` guide not being part of the documentation website before that. 
Older versions would need a link to the "stable version" `Getting started` guide. But I don't consider it that important to fix these non-prominent links.

And yes, we could remove some old versions from the documentation entirely.

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
