### PR TITLE
Update to Quarkus 2.16.7.Final

### PR DESCRIPTION
**Pull request by sophokles73**
@mattkaem Can you also take a look and see if this works for you?

### CODE REVIEW

**Comment by mattkaem** [comment]
> @mattkaem Can you also take a look and see if this works for you?

sure, thanks for the heads-up.

**Comment by mattkaem** [comment]
> @mattkaem Can you also take a look and see if this works for you?

@sophokles73 Everything seems to behave exactly as before so I see no issue with merging this. Thanks again for the heads-up :)

**Comment by sophokles73** [comment]
@calohmn would you mind taking a look?

**Review by calohmn — APPROVED** [review]
LGTM

**Pull request merged**
